package com.example.app.service;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.example.app.domain.Customer;
import com.example.app.domain.Reservation;
import com.example.app.mapper.CustomerMapper;
import com.example.app.mapper.ReservationMapper;

@Service
public class ReservationService {

	@Autowired
	private CustomerMapper customerMapper;

	@Autowired
	private ReservationMapper reservationMapper;

	@Transactional
	public void registerBooking(Customer customer, Reservation reservation) {

		customerMapper.insertCustomer(customer);

		Integer autoGeneratedCustomerId = customer.getId();

		reservation.setCustomerId(autoGeneratedCustomerId);

		// 予約ステータスを1に固定
		reservation.setStatus(1);

		reservation.setTemporaryExpiresAt(null);
		reservation.setCanceledAt(null);
		reservation.setCreatedAt(LocalDateTime.now());

		reservationMapper.insertReservation(reservation);
	}

	// 電話番号の重複チェック
	public boolean isPhoneNumberExists(String phoneNumber) {
		return customerMapper.countByPhoneNumber(phoneNumber) > 0;
	}

	//メールアドレスの重複チェック
	public boolean isEmailExists(String email) {
		return customerMapper.countByEmail(email) > 0;
	}

	public List<String> getReservedTimesByDate(String targetDate) {
		return reservationMapper.findReservedTimesByDate(targetDate);
	}
}
